FROM nginx:latest
# FROM python:latest

COPY test.html /usr/share/nginx/html

EXPOSE 80

# COPY startup.sh /usr/local/bin/startup.sh
# RUN chmod +x /usr/local/bin/startup.sh

# CMD ["/usr/local/bin/startup.sh"]
