services:
  php-apache:
    image: php:8.2-apache
    container_name: apache
    ports:
      - "2202:80"
    volumes:
      - ./public-html:/var/www/html

  db:
    image: mysql/mysql-server
    container_name: db
    environment:
      # MYSQL_ROOT_PASSWORD: my_secret_password
      # MYSQL_DATABASE: app_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "2203:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 2204:80
volumes:
  dbdata:
